# -*- coding: utf-8 -*-
"""Big Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_ujt9kRKEOANIR-M6kahBqh77AiQavfB
"""

pip install pandas numpy faker pyarrow

# Commented out IPython magic to ensure Python compatibility.
# %pip install faker

import pandas as pd
import numpy as np
from faker import Faker
import random

# Activating the Faker library
fake = Faker()

# Download data from Kaggle (after downloading the file manually or via the Kaggle API)
df = pd.read_csv("cardio_train.csv", sep=';')

# Change column names to be clear
df.rename(columns={
    'age': 'age_days',
    'ap_hi': 'systolic_bp',
    'ap_lo': 'diastolic_bp',
    'cholesterol': 'cholesterol_level',
    'gluc': 'glucose_level',
    'cardio': 'heart_disease'
}, inplace=True)

# Converting age from days to years
df['age'] = (df['age_days'] / 365).astype(int)
df.drop(columns=['age_days'], inplace=True)

# Function for creating (generating) synthetic row
def generate_synthetic_row():
    return {
        'age': random.randint(29, 80),
        'gender': random.choice([1, 2]),  # 1: نساء، 2: رجال
        'height': random.randint(140, 200),
        'weight': round(random.uniform(45, 120), 1),
        'systolic_bp': random.randint(90, 180),
        'diastolic_bp': random.randint(60, 120),
        'cholesterol_level': random.randint(1, 3),
        'glucose_level': random.randint(1, 3),
        'smoke': random.randint(0, 1),
        'alco': random.randint(0, 1),
        'active': random.randint(0, 1),
        'heart_disease': random.randint(0, 1)
    }

# Number of records to be generated
target_size = 1_000_000
current_size = df.shape[0]
needed_rows = target_size - current_size

synthetic_data = [generate_synthetic_row() for _ in range(needed_rows)]
df_synth = pd.DataFrame(synthetic_data)

# Integrating real data with synthetic_data
df_big = pd.concat([df, df_synth], ignore_index=True)

# Save results
df_big.to_csv("bigdata_heart.csv", index=False)
df_big.to_parquet("bigdata_heart.parquet", index=False)

print(f"A dataset with {df_big.shape[0]} records has been created.")

df.info()

df_big.info()

!pip install pyspark

from pyspark.sql import SparkSession
from pyspark.sql.functions import col

# Creating a Spark session
spark = SparkSession.builder \
    .appName("Heart Disease Big Data Analysis") \
    .getOrCreate()

# Reading a Parquet file (faster than CSV)
df = spark.read.parquet("bigdata_heart.parquet")

# Display 5 records to confirm reading
df.show(5)

# Display the column schema
df.printSchema()

# Check the number of records
print(f"Number of records: {df.count()}")
# Cleaning up illogical or outliers
df_clean = df.filter(
    (col("systolic_bp") > 50) & (col("systolic_bp") < 250) &
    (col("diastolic_bp") > 30) & (col("diastolic_bp") < 200) &
    (col("height") > 100) & (col("height") < 250) &
    (col("weight") > 30) & (col("weight") < 250)
)

# Save the clean copy
df_clean.write.mode("overwrite").parquet("bigdata_heart_clean.parquet")

print(f"Number of records after cleaning: {df_clean.count()}")

spark.stop()

from pyspark.sql import SparkSession
from pyspark.ml.feature import VectorAssembler, StringIndexer
from pyspark.ml.classification import LogisticRegression, RandomForestClassifier, GBTClassifier
from pyspark.ml.evaluation import MulticlassClassificationEvaluator
import time

# Creating a Spark session
spark = SparkSession.builder \
    .appName("Heart Disease Prediction with Spark MLlib") \
    .getOrCreate()

# Reading clean data
df = spark.read.parquet("bigdata_heart_clean.parquet")

# Data processing
feature_cols = ['age', 'gender', 'height', 'weight', 'systolic_bp',
                'diastolic_bp', 'cholesterol_level', 'glucose_level',
                'smoke', 'alco', 'active']

assembler = VectorAssembler(inputCols=feature_cols, outputCol="features")
df_ml = assembler.transform(df)

#Ensure that the classification column is numeric.
label_indexer = StringIndexer(inputCol="heart_disease", outputCol="label")
df_ml = label_indexer.fit(df_ml).transform(df_ml)

# Splitting data for train and test (Moved outside the function)
train_data, test_data = df_ml.randomSplit([0.8, 0.2], seed=42)


# Function for train and evaluate any model
def train_and_evaluate(model, model_name):
    start_time = time.time()
    model_fit = model.fit(train_data)
    predictions = model_fit.transform(test_data)
    elapsed_time = time.time() - start_time

    evaluator = MulticlassClassificationEvaluator(labelCol="label", predictionCol="prediction", metricName="accuracy")
    accuracy = evaluator.evaluate(predictions)

    print(f"{model_name} - Accuracy: {accuracy:.4f} - Time: {elapsed_time:.2f} sec")
    return model_name, accuracy, elapsed_time, predictions

# Logistic Regression Experiment
lr = LogisticRegression(featuresCol="features", labelCol="label", maxIter=10)
lr_model_fit = lr.fit(train_data) # Fit the model outside the function
lr_predictions = lr_model_fit.transform(test_data) # Get predictions outside the function
lr_name, lr_acc, lr_time, _ = train_and_evaluate(lr, "Logistic Regression") # Call the function to print results


# Random Forest Experiment
rf = RandomForestClassifier(featuresCol="features", labelCol="label", numTrees=50)
rf_name, rf_acc, rf_time, rf_predictions = train_and_evaluate(rf, "Random Forest") # Store RF predictions

# Gradient-Boosted Trees Experiment
gbt = GBTClassifier(featuresCol="features", labelCol="label", maxIter=20)
gbt_name, gbt_acc, gbt_time, gbt_predictions = train_and_evaluate(gbt, "Gradient-Boosted Trees") # Store GBT predictions


# عرض مقارنة النتائج
results = [(lr_name, lr_acc, lr_time), (rf_name, rf_acc, rf_time), (gbt_name, gbt_acc, gbt_time)] # Update results list
print("\n=== Model Comparison ===")
for name, acc, time_taken in results: # Update loop
    print(f"{name}: Accuracy={acc:.4f}, Time={time_taken:.2f} sec")

# Keep Spark session active for the next cell
# spark.stop()

import matplotlib.pyplot as plt
import pandas as pd

# Extract ROC curve points - Using lr_predictions from the previous cell
roc = lr_predictions.select("label", "probability").toPandas()
roc["prob_1"] = roc["probability"].apply(lambda x: float(x[1]))

from sklearn.metrics import roc_curve, auc as sk_auc

fpr, tpr, thresholds = roc_curve(roc["label"], roc["prob_1"])
roc_auc = sk_auc(fpr, tpr)

# Plot ROC curve
plt.figure(figsize=(7,6))
plt.plot(fpr, tpr, label=f"ROC curve (AUC = {roc_auc:.4f})")
plt.plot([0, 1], [0, 1], "k--")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve - Logistic Regression") # Added model name to title
plt.legend(loc="lower right")
plt.show()

!pip install xgboost

import xgboost as xgb
from sklearn.metrics import accuracy_score
import time
# from pyspark.sql import SparkSession # Import SparkSession

# Create a Spark session if one doesn't exist
# spark = SparkSession.builder \
#     .appName("XGBoost with Spark Data") \
#     .getOrCreate()

# تحويل بيانات Spark DataFrame إلى Pandas DataFrame
train_pd = train_data.toPandas()
test_pd = test_data.toPandas()

X_train = np.array(train_pd[feature_cols])
y_train = np.array(train_pd["label"])
X_test = np.array(test_pd[feature_cols])
y_test = np.array(test_pd["label"])

# XGBoost Model
start_time = time.time()
xgb_model = xgb.XGBClassifier(
    n_estimators=50,
    max_depth=5,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    eval_metric="logloss",
    use_label_encoder=False
)

xgb_model.fit(X_train, y_train)
y_pred = xgb_model.predict(X_test)

elapsed_time = time.time() - start_time
accuracy = accuracy_score(y_test, y_pred)

print(f"XGBoost - Accuracy: {accuracy:.4f} - Time: {elapsed_time:.2f} sec")

from sklearn.metrics import roc_curve, auc

y_proba = xgb_model.predict_proba(X_test)[:,1]
fpr, tpr, thresholds = roc_curve(y_test, y_proba)
roc_auc = auc(fpr, tpr)

plt.plot(fpr, tpr, label=f"XGBoost (AUC = {roc_auc:.4f})")
plt.plot([0, 1], [0, 1], "k--")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve - XGBoost")
plt.legend(loc="lower right")
plt.show()

# تثبيت المكتبات المطلوبة
!pip install xgboost

import time
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc, accuracy_score
import xgboost as xgb

# 1️⃣ Logistic Regression (Spark MLlib)
lr = LogisticRegression(featuresCol="features", labelCol="label", maxIter=10)
start_time = time.time()
lr_model = lr.fit(train_data)
lr_predictions = lr_model.transform(test_data)
lr_time = time.time() - start_time

evaluator = MulticlassClassificationEvaluator(
    labelCol="label", predictionCol="prediction", metricName="accuracy")
lr_acc = evaluator.evaluate(lr_predictions)

print(f"Logistic Regression - Accuracy: {lr_acc:.4f} - Time: {lr_time:.2f} sec")

# ROC for Logistic Regression
lr_pd = lr_predictions.select("label", "probability").toPandas()
lr_pd["prob_1"] = lr_pd["probability"].apply(lambda x: float(x[1]))
fpr_lr, tpr_lr, _ = roc_curve(lr_pd["label"], lr_pd["prob_1"])
auc_lr = auc(fpr_lr, tpr_lr)


# 2️⃣ Random Forest (Spark MLlib)
rf = RandomForestClassifier(featuresCol="features", labelCol="label", numTrees=50)
start_time = time.time()
rf_model = rf.fit(train_data)
rf_predictions = rf_model.transform(test_data)
rf_time = time.time() - start_time

rf_acc = evaluator.evaluate(rf_predictions)
print(f"Random Forest - Accuracy: {rf_acc:.4f} - Time: {rf_time:.2f} sec")

# ROC for Random Forest
rf_pd = rf_predictions.select("label", "probability").toPandas()
rf_pd["prob_1"] = rf_pd["probability"].apply(lambda x: float(x[1]))
fpr_rf, tpr_rf, _ = roc_curve(rf_pd["label"], rf_pd["prob_1"])
auc_rf = auc(fpr_rf, tpr_rf)


# 3️⃣ XGBoost (Sklearn)
train_pd = train_data.toPandas()
test_pd = test_data.toPandas()

X_train = np.array(train_pd[feature_cols])
y_train = np.array(train_pd["label"])
X_test = np.array(test_pd[feature_cols])
y_test = np.array(test_pd["label"])

start_time = time.time()
xgb_model = xgb.XGBClassifier(
    n_estimators=50,
    max_depth=5,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    eval_metric="logloss",
    use_label_encoder=False
)
xgb_model.fit(X_train, y_train)
y_pred = xgb_model.predict(X_test)
y_proba = xgb_model.predict_proba(X_test)[:,1]
xgb_time = time.time() - start_time
xgb_acc = accuracy_score(y_test, y_pred)

print(f"XGBoost - Accuracy: {xgb_acc:.4f} - Time: {xgb_time:.2f} sec")

# ROC for XGBoost
fpr_xgb, tpr_xgb, _ = roc_curve(y_test, y_proba)
auc_xgb = auc(fpr_xgb, tpr_xgb)


# 4️⃣ Plot ROC Curve for all models
plt.figure(figsize=(7,6))
plt.plot(fpr_lr, tpr_lr, label=f"Logistic Regression (AUC = {auc_lr:.4f})")
plt.plot(fpr_rf, tpr_rf, label=f"Random Forest (AUC = {auc_rf:.4f})")
plt.plot(fpr_xgb, tpr_xgb, label=f"XGBoost (AUC = {auc_xgb:.4f})")

plt.plot([0,1],[0,1],'k--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curves for Logistic Regression, Random Forest, and XGBoost")
plt.legend(loc="lower right")
plt.show()


# 5️⃣ Print Summary Table
print("\n=== Model Comparison ===")
print(f"Logistic Regression: Accuracy={lr_acc:.4f}, Time={lr_time:.2f} sec, AUC={auc_lr:.4f}")
print(f"Random Forest: Accuracy={rf_acc:.4f}, Time={rf_time:.2f} sec, AUC={auc_rf:.4f}")
print(f"XGBoost: Accuracy={xgb_acc:.4f}, Time={xgb_time:.2f} sec, AUC={auc_xgb:.4f}")